// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOgGgYJlpglWQcDMj2bbio3yqdx6zD0Zw',
    appId: '1:692954375714:web:08868eaf6e7cbe69510c7b',
    messagingSenderId: '692954375714',
    projectId: 'application-syndicate-dbdd7',
    authDomain: 'application-syndicate-dbdd7.firebaseapp.com',
    storageBucket: 'application-syndicate-dbdd7.firebasestorage.app',
    measurementId: 'G-JRZPV70H93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnETTIonwOoH3kEggEzRALM8kb-v0WY48',
    appId: '1:692954375714:android:d78aed56efcce5ec510c7b',
    messagingSenderId: '692954375714',
    projectId: 'application-syndicate-dbdd7',
    storageBucket: 'application-syndicate-dbdd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0M2Y1bJY4tQkZBWRiDRbk3e-7RwLB2zI',
    appId: '1:692954375714:ios:e0d6488ceac95256510c7b',
    messagingSenderId: '692954375714',
    projectId: 'application-syndicate-dbdd7',
    storageBucket: 'application-syndicate-dbdd7.firebasestorage.app',
    iosBundleId: 'com.example.syndicate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0M2Y1bJY4tQkZBWRiDRbk3e-7RwLB2zI',
    appId: '1:692954375714:ios:e0d6488ceac95256510c7b',
    messagingSenderId: '692954375714',
    projectId: 'application-syndicate-dbdd7',
    storageBucket: 'application-syndicate-dbdd7.firebasestorage.app',
    iosBundleId: 'com.example.syndicate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOgGgYJlpglWQcDMj2bbio3yqdx6zD0Zw',
    appId: '1:692954375714:web:cf3e3497d1f9c293510c7b',
    messagingSenderId: '692954375714',
    projectId: 'application-syndicate-dbdd7',
    authDomain: 'application-syndicate-dbdd7.firebaseapp.com',
    storageBucket: 'application-syndicate-dbdd7.firebasestorage.app',
    measurementId: 'G-K5C16T9NGV',
  );

}